### ISSUE TITLE
Mixed Content Error in Jekyll Exports

### ISSUE THREAD

**Issue by colehudson** [ecds/readux#7]
Using the book export [functionality](https://digital.library.wayne.edu/readux/books/wayne:DenslowsH1903b48447389_Readux_VirtualVolume/export/), I published a book as a jekyll site on Github Pages. My username.github.io site is a custom domain that redirects to https, so I encountered a few mixed content errors that are preventing items from loading, including jquery, marginalia.min.css, and page images. I'm betting changing to // when loading the resources will fix this. I didn't see this same issue with the [book](https://digital.library.wayne.edu/readux/books/wayne:DenslowsH1903b48447389_Readux_VirtualVolume/pages/wayne:DenslowsH1903b48447389_Readux_VirtualPage_1/) on WSU's nascent readux site.

Below is Chrome Dev Tools output for https://www.colehudson.org/humpty-dumpty/pages/1/.
![screen shot 2016-09-14 at 3 00 25 pm](https://cloud.githubusercontent.com/assets/2834861/18525810/08d45d72-7a8c-11e6-873c-de0adb028b9b.png)

**Comment by rlskoeser** [comment]
@colehudson thanks for the bug report.  We've noticed that issue too, and I think I have it fixed in the current development code - so it should be fixed in the next release.  I think it wasn't a problem before, and starting happening when GitHub made https the default for github pages sites.  

I'll leave this issue open for now, until we have a released version with a fix.
